FROM node:18.17.0 as builder 
WORKDIR /app
COPY . .
RUN npm install \
    && npm run build


FROM nginx:1.23.4
RUN apt-get update \
    && apt-get install vim -y
COPY build/nginx.conf /etc/nginx/conf.d
COPY --from=builder /app/dist  /usr/share/nginx/html
EXPOSE 6103
